export const ActionTypes = {
  SET_MOVIES: "SET_MOVIES",
  SET_SEATS: "SET_SEATS",
  SET_REQUIREDSEATS: "SET_REQUIREDSEATS",
  SELECT_SEAT: "SELECT_SEAT",
  UNSELECT_SEAT: "UNSELECT_SEAT",
  BOOK_SEAT: "BOOK_SEAT",
  UNBOOK_SEAT: "UNBOOK_SEAT"
};
